#!/bin/bash

dir="src/exec"
for file in $dir/*.c; do
	filename=$(basename "$file")
	function=$(grep -oE '\b[a-zA-Z_][a-zA-Z0-9_]*\s+[a-zA-Z_][a-zA-Z0-9_]*\([^)]*\)' "$file")
    if [ -n "$function" ]; then
        echo "/* $filename */"
        echo "$function"
        echo "--------------------"  
    fi
done
