#!/bin/bash

make fclean
norminette > norm
grep -v "OK" norm

if [ -f "out" ]; then
	rm out
fi
if [ -f "mini_log" ]; then
	rm mini_log
fi

if [ -d "scripts/output" ]; then
	rm -r scripts/output
fi

rm norm