#!/bin/bash

make fclean
if [ "$1" = "-n" ]; then
	norminette > norm
	grep -v "OK" norm
	rm norm
fi

if [ -f "out" ]; then
	rm out
fi
if [ -f "mini_log" ]; then
	rm mini_log
fi

if [ -d "scripts/output" ]; then
	rm -r scripts/output
fi
